server:
  port: 2000

# 工具参数配置
peak:
  express:
    jd:
      app-key:
      app-secret:
      rsa-secret-id:
      rsa-public-key:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 12345678

logging:
  level:
    ink.gfwl: debug
    org.springframework.web: debug